version: 2.1

jobs:
  build:
    docker:
      - image: okteto/maven:latest
    working_directory: ~/swagger-petstore
    steps:
      - checkout

      - restore_cache:
          keys:
          - maven-cache-{{ checksum "pom.xml" }}
          - maven-cache-

      - run:
          name: "install dependencies"
          command: mvn install

      - save_cache:
          paths: 
            ~/.m2/repository
          key: maven-cache-{{ checksum "pom.xml"}}

      - run:
          name: "Deploy API"
          command: mvn package jetty:run

  testing:
    docker:
      - image: circleci/python
    steps:
      - checkout

      - run:
          name: "clone testing repository"
          command: git clone git@github.com:PabloMontenegroDept/api-testing.git

      - run:
          name: "dependencies"
          command: |
            cd api-testing
            python3 -m venv venv
            sudo chown -R $USER:$USER venv/
            sudo chmod -R 755 venv/
            venv/bin/activate
            pip install -r requierement.txt

      - run:
          name: "Perform Tests"
          command: pytest --alluredir=reports
            

workflows:
  version: 2
  api-workflow:
    jobs:
      - build
      - testing:
          requires:
          -build

                

                

          
          
          
          
           
