version: 2.1

jobs:
  build:
    docker:
      - image: pablomontenegrodept/swaggerapi:final
    working_directory: ~/swagger-petstore
    steps:
      - checkout
      - run: |
          ls
          pwd
          
          
          
          
           
