version: 2.1

jobs:
  build:
    docker:
      - image: pablomontenegrodept/swaggerapi:final
    steps:
      - checkout
      - run: |
          ls
          
          
          
          
           
