version: 2.1

jobs:
  build:
    docker:
      -image: swaggerapi/petstore3:unstable
    steps:
      - checkout
      - run:
          - name: "curl"
          - command: |
              curl -X 'POST' \
              'http://localhost:8080/api/v3/pet' \
              -H 'accept: application/xml' \
              -H 'Content-Type: application/json' \
              -d '{
              "id": 10,
              "name": "doggie",
              "category": {
                "id": 1,
                "name": "Dogs"
              },
              "photoUrls": [
                "string"
              ],
              "tags": [
                {
                  "id": 0,
                  "name": "string"
                }
              ],
              "status": "available"
          }'
