version: 2.1

jobs:
  build:
    docker:
      - image: okteto/maven:latest
    working_directory: ~/swagger-petstore
    steps:
      - checkout
        #restoring cache
      - restore_cache:
          - keys:
              - maven-cache-{{ checksum "pom.xml" }}
              - maven-cache-
      - run: mvn dependency:go-offline
      - save_cache:
          path:
            ~/.m2/repository
          key: maven-cache{{ checksum "pom.xml"}}
      -run: mvn clean install

                

                

          
          
          
          
           
