version: 2.1

jobs:
  build:
    docker:
      - image: pablomontenegrodept/swaggerapi:final
    steps:
      - checkout
      - run: |
          mvn install
          cp target/lib/jetty-runner.jar /swagger-petstore/jetty-runner.jar
          cp target/*.war /swagger-petstore/server.war
          cp src/main/resources/openapi.yaml /swagger-petstore/openapi.yaml
          cp inflector.yaml /swagger-petstore/
          mvn package jetty:run
          
          
           
