version: 2.1

jobs:
  build:
    docker:
      - image: swaggerapi/petstore3:unstable
    steps:
      - checkout
      - run: curl -X 'GET' 'http://localhost:8080/api/v3/pet/findByStatus?status=available' -H 'accept: application/xml'
           
