version: 2.1

jobs:
  build:
    docker:
      - image: okteto/maven:latest
    working_directory: ~/swagger-petstore
    steps:
      - checkout
        #restoring cache
      - restore_cache:
          keys:
          - maven-cache-{{ checksum "pom.xml" }}
          - maven-cache-
          -
      - run:
          name: "install dependencies"
          command: |
            mvn install

      - save_cache:
          paths: 
            ~/.m2/repository
          key: maven-cache-{{ checksum "pom.xml"}}

      - run:
          name: "Deploy API"
          command: mvn package jetty:run

  testing:
    docker:
      - image: circleci/python
    steps:
      - checkout

      - run:
          name: "clone testing repository"
          command: |
          echo "git clone git@github.com:PabloMontenegroDept/api-testing.git" > clone.sh
          chmod -R 777 clone.sh
          ./clone.sh
          cd testing_CI

      - restore_cache:
          key:
            - test-dependencies-{{ checksum "requierements.txt"}}
            - test-dependencies-

      - run:
          name: "install dependencies"
          command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install requierements.txt

      - save_cache:
          paths: ./venv
          key: test-dependencies-{{ checksum "requierements.txt"}}

      - run:
          name: "perform tests"
          command: pytest --alluredir=reports














                

                

          
          
          
          
           
